### PR TITLE
Removed extra character in constantly.hpp; changes necessary to get xform and eggs variant working under VC++ 2015 RTM

### PR DESCRIPTION
**Pull request by dodheim**
Erroneous character causing compilation errors...

### CODE REVIEW

**Comment by dodheim** [comment]
I'm not positive the changes in `meta/common_type.hpp` have identical semantics, but it seems reasonable to me in any case... (Ambiguities may be treated differently? Does this matter?)

**Comment by dodheim** [comment]
I meant to have these commits belong to two separate PRs(the typo in prelude/constantly.hpp needs to be fixed unquestionably), but I'm new to Git and haven't gotten it yet – apologies.

**Comment by ghost** [comment]
Thanks a lot for taking your time on working this! Actually VS2015 support is important... I was a bit pessimistic about expression SFINAE, which is used in several places. I am surprised that not so much needed to be changed after all.

We require a CLA (contributor license agreement) to be signed for integrating non-trivial changes. However, sadly, the text of our CLA is not ready yet. I will get back to you with further information when we are done preparing the CLA text and procedures.

In the meantime I will study your patch and make some comments on it.

**Comment by dodheim** [comment]
Thanks, @jbo-ableton, and thank you and your company _very_ much for the library – `xform` is brilliant!.

VS2015 support is not yet complete; so far I've only done enough to make my own dependent code compile, and at present that only relies on `prelude::comp`, `xform::transduce`, `xform::filter`, `xform::map`, and `xform::repeatn`. I know that some other transducers (e.g. `unzip`) are still problematic – I'll be addressing these this week and pushing commits as I go, and I'll leave a comment here when I'm finished getting all `estd`, `meta`, `prelude`, `variant`, and `xform` tests to pass (I do not intend to use, or consequently inspect, `funken`).

---

A question while I have your attention: Is there a way for a transducer to yield multiple outputs per input rather than nesting everything inside of a `map(transduce(...))` transduction or yielding a collection and using `cat`? Nesting a `map(transduce(...))` in the outer `transduce` call is my solution at present, but it's A) repetitive, as the reducing function and state values are the same between both calls to `transduce` whenever the state is really just an identity value, and B) a common enough pattern as to be flat-out ugly to see all over the place – _some_ abstraction is warranted here. I'd be fine with using `cat`, but the overhead from allocating the nested containers quickly becomes noticeable and is ultimately unnecessary. I'd ask for the direct equivalent of an existing Clojure transducer (assuming there is one), but alas, I'm an ML man _much_ moreso than Lisp and don't know the Clojure API; in case you're sufficiently familiar with OCaml or F#, I'm looking for a moral equivalent of [`Seq.collect`](https://msdn.microsoft.com/en-us/library/ee340468.aspx). Thanks and regards,

**Comment by ghost** [comment]
Hi again @dodheim! Sorry for the late reply.

On your question, there are several ways a transducer can yield multiple values, but it's hard to give a recomendations without further details. All transducers that call `reduce_nested` produce multiple values -- you can `grep` the code for that to find them, for now, they are `cat`, `chain` and `product`. Other transducers like `interleave` can be considered to produce more than one output. For example, if you are concerned of the expensiveness of returning a `std::vector` and then using `cat`, an alternative (if you have a compile-time determined number of results), is to return a `std::tuple<>` or `std::array<>` and then use `comp(unzip, interleave)` to expand the result into the resulting sequence.

**Comment by ghost** [comment]
Another interesting data-point, I guess since you call `transduce` inside your `map(...)` mapping, you do have a collection at hand inside the map. In this case, note that transducers use move-semantics, so returning the collection **does not** result in the collection being copied before passing it to `cat(...)`, but the collection is passed as r-value reference instead.

You can use the framework in `atria/testing/benchmark.hpp` to setup a benchmark to validate these assumptions. My stimate is that yielding a collection from a map and then catting it should be as fast, or possibly even faster, than transducing the collection inside the map.

**Comment by ghost** [comment]
(In case you read the previous comment by email, I just edited it, note the bold text :smile:)

**Comment by ghost** [comment]
@dodheim, in the meantime I've added continuous integration support and fixed the problem with the extra character. You may want to rebase your branch on master, dropping your first commit. This way your branch will be tested against GCC and Clang on the Travis servers as you develop it.

**Comment by toh-ableton** [comment]
There seems to be no activity on this PR, closing for now. Please re-open if this is still current.

CC @arximboldi

**Comment by arximboldi** [comment]
Thanks @toh-ableton!

**Pull request closed without merging**
